import localFont from 'next/font/local'
import { Geist, Geist_Mono, Poppins } from "next/font/google";

import "./globals.css";

const analogue = localFont({
  src: [
    {
      path: "./fonts/Analogue-Font/analogue-webfont.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Analogue-Font/analogue-italic-webfont.ttf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-analogue",
});

const editorsLight = localFont({
  src: [
    {
      path: "./fonts/Editor-Light/Editor-Light.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-editors-light",
});

const creattion = localFont({
  src: [
    {
      path: "./fonts/creattion/Creattion-Demo.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-creattion",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["400", "600", "700"], 
  variable: "--font-poppins"
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${analogue.variable} ${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${editorsLight.variable} ${creattion.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
